version: "3.9"
services:

  reverse_proxy:
    container_name: reverse-proxy
    image: nginx:1.17.10
    volumes:
      - type: bind
        source: ./Lab5_Reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - proxy-app-network

  front-app:
    container_name: front-app
    image: front-app:latest
    build: 
      context: ./
      dockerfile: Dockerfile-front
    # ports:
    #   - "8083:80"
    networks:
      - proxy-app-network
  
  gateway-app:
    container_name: gateway-app
    image: gateway-app:latest
    build: 
      context: ./
      dockerfile: Dockerfile-gateway
    # ports:
    #   - "8080:8080"
    networks:
      - proxy-app-network
      - app-inner-network

  film-app:
    container_name: film-app
    image: film-app:latest
    build: 
      context: ./
      dockerfile: Dockerfile-film
    # ports:
    #   - "8082:8082"
    networks:
      - app-inner-network
  
  director-app:
    container_name: director-app
    image: director-app:latest
    build:
      context: ./
      dockerfile: Dockerfile-director
    # ports:
    #   - "8081:8081"
    depends_on:
      - film-app
    restart: on-failure
    networks:
      - app-inner-network

networks:
  app-inner-network:
    name: app-inner-network 
    driver: bridge
  proxy-app-network:
    name: proxy-app-network
    driver: bridge