GET http://localhost:8082/api/films
###

GET http://localhost:8082/api/directors/4/films
###

POST http://localhost:8082/api/directors/4/films
Content-Type: application/json

{
  "title": "The Hobbit: An Unexpected Journey",
  "releaseYear": "2012"
}
###

DELETE http://localhost:8082/api/directors/4/films/10
###






GET http://localhost:8081/api/directors
###

GET http://localhost:8081/api/directors/4
###

POST http://localhost:8081/api/directors
Content-Type: application/json

{
  "name": "George",
  "surname": "Lucas",
  "dateOfBirth": "1944-05-14"
}
###

DELETE http://localhost:8081/api/directors/1
###